---
title: "lab 7 spatial data"
author: "Alicia Canales"
date: "2023-02-23"
output: html_document
---

```{r setup, echo=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(here)
library(broom)


### Spatial Packages
library(sf)
library(tmap)
```

### Reading in data
```{r}
ca_counties_sf <- read_sf(here('data/ca_counties/CA_Counties_TIGER2016.shp'))

ca_subset_sf <- ca_counties_sf %>% 
  janitor::clean_names() %>% 
  select(county_name = name,
         land_area = aland)

ca_subset_df <- ca_subset_sf %>% 
  as.data.frame() %>% 
  select(-geometry) # dropping the sticky geometry if need be
```

#### Check and set the CRS
```{r}
ca_subset_sf %>% 
  st_crs() #EPSG.. keeping track of this?

ggplot() +
  geom_sf(data = ca_subset_sf, aes(fill = land_area),
          color = 'white',
          size = 0.1) +
  scale_fill_gradientn( colors = c('cyan', 'blue', 'purple')) + # 'scale_fill_gradientn' lets you add your own colors
  theme_void() 
```


### Load another data set on an invasive species
```{r}
sesbania_sf <- read_sf(here('data', 'red_sesbania/ds80.shp')) %>% 
  janitor::clean_names()

sesbania_sf %>% 
  st_crs()

sesbania_3857_sf <- sesbania_sf %>% 
  st_transform(3857) # transforming crs to crs 


```


### Plotting the two together
```{r}
ggplot()+
  geom_sf(data = ca_subset_sf, fill = 'grey30')+ # the first geom_sf will be on the bottom and the rest will layer on top. Bottom up
  geom_sf(data = sesbania_3857_sf, 
          size = 1,
          color = 'red') 
```

```{r}
ca_sesb_sf <- ca_subset_sf %>% 
  st_join(sesbania_3857_sf)

sesb_counts_sf <- ca_sesb_sf %>% 
  group_by(county_name) %>% 
  summarize(n_records = sum(!is.na(id))) # all the ones where it is not na it get a true but in counts = 0 
```


### Plot the results(choropleth map)
```{r}
ggplot(data = sesb_counts_sf) %>% 
  mutate(n_records = ifelse(n_records == 0, NA, n_records)) +
  geom_sf(data = n_records, color = 'blue') +
  geom_sf(aes(fill = sesbania_3857_sf), color = 'grey70', size = 0.1) +
  scale_fill_gradientn(colors = c('yellow', 'orange', 'red'), na.value = 'grey90')
```

###Plot just the points in solano county
```{r}
solano_sesb_sf <- sesbania_3857_sf %>% 
  filter(county == 'Solano')

solano_sf <- ca_subset_sf %>% 
  filter(county_name == 'Solano')

ggplot() +
  geom_sf(data = solano_sf) +
  geom_sf(data = solano_sesb_sf, color = 'red')
```

### Make an interactive map
```{r}
## Set tmap interactive mode
tmap_mode('plot') # either ' view ' or 'plot' for different maps

tm_shape(ca_subset_sf) +
  tm_fill('land_area', palette = 'BuGn') +
  tm_shape(sesbania_3857_sf) +
  tm_dots()
```












